import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'es' | 'fr';

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.register': 'Sign Up',
    'nav.logout': 'Logout',
    'hero.title': 'TRANSFORM YOUR BODY',
    'hero.subtitle': 'UNLEASH YOUR POTENTIAL',
    'hero.desc': 'Track workouts, monitor progress, and build the body you\'ve always wanted with GoFitness.',
    'hero.cta': 'Start Your Journey',
    'hero.cta2': 'Learn More',
    'features.title': 'WHY GOFITNESS?',
    'features.subtitle': 'Everything you need to crush your fitness goals',
    'features.track': 'Track Workouts',
    'features.track.desc': 'Log every rep, set, and exercise with our intuitive tracking system.',
    'features.progress': 'Monitor Progress',
    'features.progress.desc': 'Watch your body transform with detailed measurements and charts.',
    'features.muscle': 'Muscle Tracking',
    'features.muscle.desc': 'Track muscle gains across all body groups with precision.',
    'features.goals': 'Set Goals',
    'features.goals.desc': 'Define targets and smash through them with guided programs.',
    'features.community': 'Community',
    'features.community.desc': 'Connect with like-minded athletes and share your journey.',
    'features.analytics': 'Smart Analytics',
    'features.analytics.desc': 'AI-powered insights to optimize your training and nutrition.',
    'pricing.title': 'CHOOSE YOUR PLAN',
    'pricing.subtitle': 'Start free, upgrade when ready',
    'pricing.free': 'Starter',
    'pricing.pro': 'Pro',
    'pricing.elite': 'Elite',
    'pricing.free.price': '$0',
    'pricing.pro.price': '$19',
    'pricing.elite.price': '$49',
    'pricing.mo': '/month',
    'pricing.cta': 'Get Started',
    'pricing.popular': 'Most Popular',
    'testimonials.title': 'REAL RESULTS',
    'testimonials.subtitle': 'From our community',
    'footer.rights': '© 2026 GoFitness. All rights reserved.',
    'auth.login': 'Sign In',
    'auth.register': 'Create Account',
    'auth.forgot': 'Forgot Password?',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Full Name',
    'auth.confirm_password': 'Confirm Password',
    'auth.reset': 'Reset Password',
    'auth.back_login': 'Back to Sign In',
    'auth.no_account': "Don't have an account?",
    'auth.has_account': 'Already have an account?',
    'auth.reset_sent': 'Check your email for reset instructions',
    'auth.new_password': 'New Password',
    'dashboard.title': 'Dashboard',
    'dashboard.workouts': 'Workouts',
    'dashboard.progress': 'Progress',
    'dashboard.add_workout': 'Log Workout',
    'dashboard.add_progress': 'Log Progress',
    'profile.title': 'Profile',
    'profile.edit': 'Edit Profile',
    'profile.save': 'Save Changes',
    'admin.title': 'Admin Panel',
    'admin.users': 'Users',
    'admin.workouts': 'All Workouts',
    'admin.stats': 'Statistics',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.features': 'Características',
    'nav.pricing': 'Precios',
    'nav.dashboard': 'Panel',
    'nav.profile': 'Perfil',
    'nav.admin': 'Admin',
    'nav.login': 'Ingresar',
    'nav.register': 'Registrarse',
    'nav.logout': 'Salir',
    'hero.title': 'TRANSFORMA TU CUERPO',
    'hero.subtitle': 'LIBERA TU POTENCIAL',
    'hero.desc': 'Registra entrenamientos, monitorea progreso y construye el cuerpo que siempre quisiste.',
    'hero.cta': 'Comienza Tu Viaje',
    'hero.cta2': 'Saber Más',
    'features.title': '¿POR QUÉ GOFITNESS?',
    'features.subtitle': 'Todo lo que necesitas para alcanzar tus metas fitness',
    'features.track': 'Registra Entrenamientos',
    'features.track.desc': 'Registra cada repetición y serie con nuestro sistema intuitivo.',
    'features.progress': 'Monitorea Progreso',
    'features.progress.desc': 'Observa tu transformación con medidas detalladas y gráficos.',
    'features.muscle': 'Seguimiento Muscular',
    'features.muscle.desc': 'Rastrea ganancias musculares en todos los grupos con precisión.',
    'features.goals': 'Define Metas',
    'features.goals.desc': 'Establece objetivos y supéralos con programas guiados.',
    'features.community': 'Comunidad',
    'features.community.desc': 'Conéctate con atletas y comparte tu camino.',
    'features.analytics': 'Análisis Inteligente',
    'features.analytics.desc': 'Insights con IA para optimizar tu entrenamiento.',
    'pricing.title': 'ELIGE TU PLAN',
    'pricing.subtitle': 'Comienza gratis, mejora cuando quieras',
    'pricing.free': 'Inicio',
    'pricing.pro': 'Pro',
    'pricing.elite': 'Elite',
    'pricing.free.price': '$0',
    'pricing.pro.price': '$19',
    'pricing.elite.price': '$49',
    'pricing.mo': '/mes',
    'pricing.cta': 'Comenzar',
    'pricing.popular': 'Más Popular',
    'testimonials.title': 'RESULTADOS REALES',
    'testimonials.subtitle': 'De nuestra comunidad',
    'footer.rights': '© 2026 GoFitness. Todos los derechos reservados.',
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Crear Cuenta',
    'auth.forgot': '¿Olvidaste tu contraseña?',
    'auth.email': 'Correo',
    'auth.password': 'Contraseña',
    'auth.name': 'Nombre Completo',
    'auth.confirm_password': 'Confirmar Contraseña',
    'auth.reset': 'Restablecer Contraseña',
    'auth.back_login': 'Volver a Iniciar Sesión',
    'auth.no_account': '¿No tienes cuenta?',
    'auth.has_account': '¿Ya tienes cuenta?',
    'auth.reset_sent': 'Revisa tu correo para instrucciones',
    'auth.new_password': 'Nueva Contraseña',
    'dashboard.title': 'Panel',
    'dashboard.workouts': 'Entrenamientos',
    'dashboard.progress': 'Progreso',
    'dashboard.add_workout': 'Registrar Entrenamiento',
    'dashboard.add_progress': 'Registrar Progreso',
    'profile.title': 'Perfil',
    'profile.edit': 'Editar Perfil',
    'profile.save': 'Guardar',
    'admin.title': 'Panel Admin',
    'admin.users': 'Usuarios',
    'admin.workouts': 'Todos los Entrenamientos',
    'admin.stats': 'Estadísticas',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.features': 'Fonctionnalités',
    'nav.pricing': 'Tarifs',
    'nav.dashboard': 'Tableau de bord',
    'nav.profile': 'Profil',
    'nav.admin': 'Admin',
    'nav.login': 'Connexion',
    'nav.register': "S'inscrire",
    'nav.logout': 'Déconnexion',
    'hero.title': 'TRANSFORMEZ VOTRE CORPS',
    'hero.subtitle': 'LIBÉREZ VOTRE POTENTIEL',
    'hero.desc': 'Suivez vos entraînements, surveillez vos progrès et construisez le corps dont vous avez toujours rêvé.',
    'hero.cta': 'Commencez Maintenant',
    'hero.cta2': 'En Savoir Plus',
    'features.title': 'POURQUOI GOFITNESS ?',
    'features.subtitle': 'Tout ce dont vous avez besoin pour atteindre vos objectifs',
    'features.track': 'Suivi Entraînements',
    'features.track.desc': 'Enregistrez chaque répétition avec notre système intuitif.',
    'features.progress': 'Suivre les Progrès',
    'features.progress.desc': 'Observez votre transformation avec des mesures détaillées.',
    'features.muscle': 'Suivi Musculaire',
    'features.muscle.desc': 'Suivez vos gains musculaires avec précision.',
    'features.goals': 'Définir des Objectifs',
    'features.goals.desc': 'Fixez des cibles et dépassez-les avec des programmes guidés.',
    'features.community': 'Communauté',
    'features.community.desc': 'Connectez-vous avec des athlètes partageant vos objectifs.',
    'features.analytics': 'Analyses Intelligentes',
    'features.analytics.desc': "Insights IA pour optimiser votre entraînement.",
    'pricing.title': 'CHOISISSEZ VOTRE PLAN',
    'pricing.subtitle': 'Commencez gratuitement',
    'pricing.free': 'Starter',
    'pricing.pro': 'Pro',
    'pricing.elite': 'Élite',
    'pricing.free.price': '0€',
    'pricing.pro.price': '19€',
    'pricing.elite.price': '49€',
    'pricing.mo': '/mois',
    'pricing.cta': 'Commencer',
    'pricing.popular': 'Le Plus Populaire',
    'testimonials.title': 'RÉSULTATS RÉELS',
    'testimonials.subtitle': 'De notre communauté',
    'footer.rights': '© 2026 GoFitness. Tous droits réservés.',
    'auth.login': 'Se Connecter',
    'auth.register': 'Créer un Compte',
    'auth.forgot': 'Mot de passe oublié ?',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.name': 'Nom Complet',
    'auth.confirm_password': 'Confirmer le mot de passe',
    'auth.reset': 'Réinitialiser',
    'auth.back_login': 'Retour à la connexion',
    'auth.no_account': "Pas de compte ?",
    'auth.has_account': 'Déjà un compte ?',
    'auth.reset_sent': 'Vérifiez votre email pour les instructions',
    'auth.new_password': 'Nouveau Mot de Passe',
    'dashboard.title': 'Tableau de Bord',
    'dashboard.workouts': 'Entraînements',
    'dashboard.progress': 'Progrès',
    'dashboard.add_workout': 'Enregistrer Entraînement',
    'dashboard.add_progress': 'Enregistrer Progrès',
    'profile.title': 'Profil',
    'profile.edit': 'Modifier le Profil',
    'profile.save': 'Sauvegarder',
    'admin.title': "Panneau d'Administration",
    'admin.users': 'Utilisateurs',
    'admin.workouts': 'Tous les Entraînements',
    'admin.stats': 'Statistiques',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('gf-lang') as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('gf-lang', language);
  }, [language]);

  const t = (key: string) => translations[language]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
